"""从实际解析树和 ///、//! 注释生成可读 API 清单，不执行注释里的代码。

使用原始模块 AST 而非内部改名后的 AST，保持用户名称与源码位置。
首版生成 Markdown 或 JSON；不是完整文档站点/文档测试系统。
"""
import re

from .xe_ast.ast import SYNTAX_VERSION
from .xe_ast.modules import ModuleLoader
from .xe_ast.semantic import Checker


def preceding_docs(source, comments, node) -> str:
    cursor = node["span"]["start"]["offset"]
    result = []
    for comment in reversed(comments):
        start, end = comment["span"]["start"]["offset"], comment["span"]["end"]["offset"]
        if end > cursor:
            continue
        if source.text[end:cursor].strip() or not comment["raw"].startswith("///"):
            break
        result.append(comment["raw"][3:].removeprefix(" "))
        cursor = start
    return "\n".join(reversed(result))


def signature(source, node) -> str:
    start, end = node["span"]["start"]["offset"], node["span"]["end"]["offset"]
    if node.get("body"):
        end = node["body"]["span"]["start"]["offset"]
    text = source.text[start:end].strip()
    if node["kind"] in {"Struct", "Enum", "Trait", "Impl"}:
        text = text.split("{", 1)[0].strip()
    return text


def collect(source, private=False):
    loader = ModuleLoader(source)
    source_info, tree = loader.program()
    checker = Checker(source_info, tree)
    errors = checker.check()
    if errors:
        raise errors[0]
    modules = []
    for module in loader.modules.values():
        # 本地依赖可达以便检查，但不把别人的源码当成本包 API。
        if module.package is not loader.entry_module.package:
            continue
        symbols = []
        comments = module.tree["comments"]

        # 显式绑定本次模块的数据；这个函数不会依赖下一轮循环的变量。
        def add(node, name=None, visible=None, *, module=module, comments=comments, symbols=symbols):
            if not private and not (node.get("public") if visible is None else visible):
                return
            symbols.append({"name": name or node.get("name", ""), "kind": node["kind"],
                            "signature": signature(module.source, node),
                            "documentation": preceding_docs(module.source, comments, node),
                            "source": module.source.filename, "span": node["span"]})

        for item in module.tree["items"]:
            kind = item["kind"]
            if kind == "Impl":
                target = item["target"]
                if target["kind"] == "NamedType" and len(target["path"]["parts"]) == 1:
                    declaration = module.declarations.get(target["path"]["parts"][0])
                    if declaration and not declaration["public"] and not private:
                        continue
                owner = signature(module.source, item)
                for method in item["methods"]:
                    add(method, owner + "::" + method["name"])
            elif kind == "Extern":
                for function in item["functions"]:
                    add(function)
            elif kind == "Use" and item["public"]:
                add(item, "::".join(item["path"]["parts"]))
            else:
                add(item)
                for field in item.get("fields", []):
                    add(field, item["name"] + "." + field["name"], item["public"] and field["public"])
                for variant in item.get("variants", []):
                    add(variant, item["name"] + "::" + variant["name"], item["public"])
                for method in item.get("methods", []):
                    add(method, item["name"] + "::" + method["name"], item["public"])
        modules.append({"module": "::".join(("crate", *module.path)),
                        "source": module.source.filename,
                        "documentation": "\n".join(comment["raw"][3:].removeprefix(" ")
                            for comment in comments if comment["raw"].startswith("//!")),
                        "symbols": symbols})
    return {"schema_version": 1, "syntax_version": SYNTAX_VERSION, "modules": modules}, checker.warnings, tree["_sources"]


def markdown(data, title="Xe API") -> str:
    result = [f"# {title}", "", "<!-- Generated by xe doc; do not edit. -->", ""]
    for module in data["modules"]:
        result += [f"## {module['module']}", "", module["documentation"], ""]
        for symbol in module["symbols"]:
            # 常量字符串可能包含反引号；代码围栏必须比内容的最长序列长。
            maximum = max((len(match) for match in re.findall(r"`+", symbol["signature"])), default=0)
            fence = "`" * max(3, maximum + 1)
            result += [f"### {symbol['name']}", "", f"{fence}xe", symbol["signature"], fence,
                       "", symbol["documentation"], "",
                       f"源码：{symbol['source']}:{symbol['span']['start']['line']}", ""]
    return "\n".join(result).rstrip() + "\n"
